### ISSUE TITLE
Room names should be strings

### ISSUE THREAD

**Issue by sbecot** [Sparika/ACOR_SDP#2]
It is possible to create room named with a string but only numbered room are listed.
A room name should be a string. Characters allowed are: 0-9 a-z A-Z

**Comment by Sparika** [comment]
Room name should be [0-9a-zA-Z]* and not [0-9a-zA-Z]*[a-zA-Z] @IdirB  ;)

Actually, there is no need to check the room name format, just accept String instead of number only. ;)

**Comment by IdirB** [comment]
fixed width a pattern accept just number or letters or numbers and letters and a name of room is required
